/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#363941",
        "surface-container-low": "#181c23",
        "c2pa-wellformed": "#60A5FA",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#b9c8de",
        "atproto-blue": "#0085FF",
        "on-error": "#690005",
        "surface-dim": "#10131b",
        secondary: "#b9c8de",
        "c2pa-invalid": "#F87171",
        surface: "#10131b",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-lowest": "#0a0e15",
        "primary-fixed-dim": "#a9c7ff",
        "on-tertiary-container": "#00311f",
        "inverse-surface": "#e0e2ec",
        "status-public": "#10B981",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#c0c6d6",
        "tertiary-container": "#00a572",
        "on-primary": "#003063",
        "surface-variant": "#31353d",
        "c2pa-trusted": "#34D399",
        "on-secondary": "#233143",
        tertiary: "#4edea3",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "secondary-fixed": "#d4e4fa",
        "on-secondary-container": "#a7b6cc",
        "inverse-primary": "#005db6",
        "outline-variant": "#404754",
        "status-permissioned": "#8B5CF6",
        "surface-container": "#1c2027",
        "surface-container-highest": "#31353d",
        "secondary-container": "#39485a",
        "tertiary-fixed": "#6ffbbe",
        "inverse-on-surface": "#2d3038",
        primary: "#a9c7ff",
        "on-tertiary": "#003824",
        "on-primary-fixed-variant": "#00468b",
        "on-background": "#e0e2ec",
        "slate-900": "#0F172A",
        "on-secondary-fixed": "#0d1c2d",
        "on-tertiary-fixed": "#002113",
        "status-unlisted": "#F59E0B",
        "on-secondary-fixed-variant": "#39485a",
        "primary-container": "#3a90ff",
        "surface-tint": "#a9c7ff",
        outline: "#8a91a0",
        "on-primary-fixed": "#001b3d",
        "on-primary-container": "#002957",
        "slate-800": "#1E293B",
        background: "#10131b",
        "on-surface": "#e0e2ec",
        "surface-container-high": "#262a32",
        "primary-fixed": "#d6e3ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "panel-padding": "1.25rem",
        "container-max-width": "1440px",
        "grid-margin": "2rem",
        "stack-sm": "0.5rem",
        "grid-gutter": "1.5rem",
        "stack-md": "1rem",
      },
      fontFamily: {
        "body-base": ["Inter", "sans-serif"],
        "headline-md-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "metadata-code": ["JetBrains Mono", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        "disclosure-l1": ["Inter", "sans-serif"],
        "material-symbols": ["Material Symbols Outlined", "sans-serif"],
      },
      fontSize: {
        "body-base": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "metadata-code": ["13px", { lineHeight: "16px", fontWeight: "500" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "disclosure-l1": ["14px", { lineHeight: "20px", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};