#!/usr/bin/env bash
# Download fonts and images into assets/ for fully offline GitHub Pages hosting.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FONTS_DIR="$ROOT/assets/fonts"
IMAGES_DIR="$ROOT/assets/images"
CSS_DIR="$ROOT/assets/css"

mkdir -p "$FONTS_DIR" "$IMAGES_DIR" "$CSS_DIR"

copy_font_file() {
  local family="$1"
  local filename="$2"
  local src="$ROOT/node_modules/@fontsource/${family}/files/${filename}"
  if [[ ! -f "$src" ]]; then
    echo "Missing font file: ${src}" >&2
    exit 1
  fi
  cp "$src" "$FONTS_DIR/"
}

echo "Copying required latin font files..."
copy_font_file "inter" "inter-latin-400-normal.woff2"
copy_font_file "inter" "inter-latin-500-normal.woff2"
copy_font_file "inter" "inter-latin-600-normal.woff2"
copy_font_file "inter" "inter-latin-700-normal.woff2"
copy_font_file "hanken-grotesk" "hanken-grotesk-latin-600-normal.woff2"
copy_font_file "hanken-grotesk" "hanken-grotesk-latin-700-normal.woff2"
copy_font_file "jetbrains-mono" "jetbrains-mono-latin-500-normal.woff2"

echo "Downloading Material Symbols Outlined..."
curl -fsSL \
  "https://fonts.gstatic.com/s/materialsymbolsoutlined/v205/kJEhBvYX7BgnkSrUwT8OhrdQw4oELdPIeeII9v6oFsI.woff2" \
  -o "$FONTS_DIR/material-symbols-outlined.woff2"

cat > "$CSS_DIR/fonts.css" <<'EOF'
/* Self-hosted fonts — generated by scripts/vendor-assets.sh */
@font-face {
  font-family: "Inter";
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url("../fonts/inter-latin-400-normal.woff2") format("woff2");
}
@font-face {
  font-family: "Inter";
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url("../fonts/inter-latin-500-normal.woff2") format("woff2");
}
@font-face {
  font-family: "Inter";
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url("../fonts/inter-latin-600-normal.woff2") format("woff2");
}
@font-face {
  font-family: "Inter";
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url("../fonts/inter-latin-700-normal.woff2") format("woff2");
}
@font-face {
  font-family: "Hanken Grotesk";
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url("../fonts/hanken-grotesk-latin-600-normal.woff2") format("woff2");
}
@font-face {
  font-family: "Hanken Grotesk";
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url("../fonts/hanken-grotesk-latin-700-normal.woff2") format("woff2");
}
@font-face {
  font-family: "JetBrains Mono";
  font-style: normal;
  font-weight: 500;
  font-display: swap;
  src: url("../fonts/jetbrains-mono-latin-500-normal.woff2") format("woff2");
}
@font-face {
  font-family: "Material Symbols Outlined";
  font-style: normal;
  font-weight: 100 700;
  font-display: block;
  src: url("../fonts/material-symbols-outlined.woff2") format("woff2");
}
EOF

echo "Downloading homepage images..."
curl -fsSL "https://lh3.googleusercontent.com/aida-public/AB6AXuCRZygQBAFTZg3xYt7-cJY1gT5trDjkLk_kGKRDSl5nZvr6RFltF9NXQF_8pFYqEf1D7qHBB9rzhXPnIn-YHy8cSgTBKE--KY-gnwwZ6vwwTIrIjLIF3Rdaz4tee_1VaiLKhuLEJEenQWEm0NqEzXCnVD1dxyJ-8amJ3ze5VgWN547Sd22JgjrL7JG37Ijdq9c39lzzGbv-tyPo0R1d6PMmNoeyjHX8UKi0zmu0jRFQHUgKgGaxu4UBb3iEuen6Plq9mckVKUYmBIM-" \
  -o "$IMAGES_DIR/avatar.jpg"
curl -fsSL "https://lh3.googleusercontent.com/aida-public/AB6AXuD0mdoo8eBhe4a3gvBOVJSbcOcHC9d_XRm7FjwdGbS8bUIbfZ9Lr4L57oSfqL1x5nI87f0bwh3QXBeMJG81i0Ac1LVBbFKJSeYHmeyG8YFdjc1l1QIP4regAqzit7rzJVEuL-H1HLY_P4rHp9CgJ-OP6q6E7VCncFg4KBKqBIqffP4Qq_zzmQgScxoRnaEuhrU2OpXSCz9zgmkq6caLrP7M7vjFOlyahEil_zjDH3QrDmfEUpW2eVXJWCZmJzqkesz1El3p4LBKLnou" \
  -o "$IMAGES_DIR/c2pa-visual.jpg"
curl -fsSL "https://lh3.googleusercontent.com/aida-public/AB6AXuDatEdBtyNvzmgrzA3BTPbKUGLo0QvfCbqyZIgnS92PHzZvI_Um9PY5LS522LLw5k-mM7JhXKCW7CEmJ7W7teRRh6DE_hSQV85NNB5eZKhA-9q0SDKKi0chohVm_Xzh8HtW-bTq6wvmVHXMZ21soLndANk58LT5t3JpKyJdxgabN0PirRFoKccDIEiOsT0D_18Vw3DG2Tpjl5bLAkdjd7Dl5upsK6xI6o1fsi2Vdgwruq2SeFwKW6i9P68ygJdLyhknDqYKfBPsFvgv" \
  -o "$IMAGES_DIR/gallery-thumb.jpg"

echo "Assets vendored under assets/"